name: SonarQube
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Pre-install Jenkins Extensions
        run: |
          # Manually download the extension that is causing the bootstrap failure
          mvn -B -s jenkins-settings.xml dependency:get \
            -Dartifact=io.jenkins.tools.incrementals:git-changelist-maven-extension:1.13:jar \
            -DremoteRepositories=https://repo.jenkins-ci.org/incrementals/
          
          # Manually download the POM for that extension (the 'artifact descriptor')
          mvn -B -s jenkins-settings.xml dependency:get \
            -Dartifact=io.jenkins.tools.incrementals:git-changelist-maven-extension:1.13:pom \
            -DremoteRepositories=https://repo.jenkins-ci.org/incrementals/

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_VCATEST }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          mvn -B -U 
          -s jenkins-settings.xml 
          verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -DskipTests
          -Dspotbugs.skip=true
          -Dsonar.projectKey=vcatest_jenkins
          -Dsonar.organization=vcatest
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.c.file.suffixes=-
          -Dsonar.cpp.file.suffixes=-
          -Dsonar.objc.file.suffixes=-
