name: SonarQube
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          # We temporary disable the cache to ensure a fresh, clean environment
          # once it works, we can re-enable it.
          # cache: 'maven'

      - name: Nuke Broken Cache
        run: |
          rm -rf ~/.m2/repository/io/jenkins
          rm -rf ~/.m2/repository/org/jenkins-ci
          rm -rf ~/.m2/repository/org/apache/maven/resolver

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_VCATEST }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          mvn -B -U 
          -gs jenkins-settings.xml 
          verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -DskipTests
          -Dspotbugs.skip=true
          -Dmaven.wagon.http.retryHandler.count=10
          -Dmaven.wagon.http.retryHandler.class=default
          -Dsonar.projectKey=vcatest_jenkins
          -Dsonar.organization=vcatest
          -Dsonar.host.url=https://sonarcloud.io
