name: Embold Code Quality Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  embold-scan_fc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Remove non-breaking spaces from XML files
        run: |
          find . -name "*.xml" -print0 | while IFS= read -r -d '' file; do
            sed -i 's/\xC2\xA0/ /g' "$file"
          done

      - name: Build with Maven and Run Analysis
        run: mvn -B clean verify -DskipTests

      - name: Download and Extract Scanner
        run: |
          curl ${{ vars.EMBOLD_SCANNER_URL }} -o browserstack-codequality-scanner-archive.tar.gz
          tar xvf browserstack-codequality-scanner-archive.tar.gz

      - name: Download Repository Configuration
        run: |
          curl --silent --location --request GET "${{ vars.EMBOLD_URL_JAVA }}/api/v1/repositories/af3f6fe7fd89509802cafcbcbe7bb69b/scans/config/download" \
            --header "Authorization: Bearer ${{ secrets.EMBOLD_TOKEN_JAVA }}" \
            -o repository-configuration.json

      - name: Run Embold Scanner
        env:
          EMBOLD_TOKEN: ${{ secrets.EMBOLD_TOKEN_JAVA }}
        run: |
          ./browserstack-codequality-scanner/bin/embold-scanner analyse \
            -u ${{ vars.EMBOLD_URL_JAVA }} \
            -t $EMBOLD_TOKEN \
            -r af3f6fe7fd89509802cafcbcbe7bb69b \
            -b . \
            -d ./embold-data \
            -c ./repository-configuration.json \
            -l ./embold-log \
            -sh ./embold-scanner-home \
            -v
